# Troubleshooting eCAT Workflows

Use this notebook when loading, plotting, units, references, normalization, or peak detection does not behave as expected. It uses the packaged example data so you can separate package/setup issues from data-specific issues.

In [1]:
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import pandas as pd

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent


def display_path(path):
    path = Path(path)
    try:
        return str(path.resolve().relative_to(ROOT.resolve()))
    except ValueError:
        return path.name

if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

import ecat as e

DATA_DIR = ROOT / "examples" / "data" / "fe_phoh_cv"
EXPORT_DIR = ROOT / "notebooks" / "_outputs"
EXPORT_DIR.mkdir(exist_ok=True)

e.plotting_style("notebook")
print("eCAT version:", getattr(e, "__version__", "unknown"))
print("Example data:", display_path(DATA_DIR))
print("Text files:", len(list(DATA_DIR.glob("*.txt"))))

eCAT version: 0.1.0b2
Example data: examples/data/fe_phoh_cv
Text files: 13

In [2]:
cvs = e.get_data({
    "folder path": str(DATA_DIR),
    "recursive search": False,
    "reference mode": "none",
    "print": False,
})
cvs = e.filter(cvs, {"segments": 3}, {"print": False})
print(f"Loaded {len(cvs)} CV objects")
print(sorted({type(obj).__name__ for obj in cvs}))

Searching exclusively through:
 examples/data/fe_phoh_cv
13 .txt files found.

Loaded 12 CV objects
['cv']

In [3]:
print("If this loads 10 CV objects, your basic import and parser path works.")
print("Loaded:", len(cvs))
print("Types:", sorted({type(obj).__name__ for obj in cvs}))

If this loads 10 CV objects, your basic import and parser path works.
Loaded: 12
Types: ['cv']

In [4]:
# Check what eCAT parsed from filenames.
parsed = pd.DataFrame([
    {
        "name": obj.name,
        "gas": getattr(obj, "gas", None),
        "solvent": getattr(obj, "solvent", None),
        "scan_rate": getattr(obj, "scan_rate", None),
        "scan_window": getattr(obj, "scan_window", None),
        "compounds": ", ".join(map(str, getattr(obj, "compounds", []))),
    }
    for obj in cvs
])
parsed

,name,gas,solvent,scan_rate,scan_window,compounds
0,MeCN_Ar_0.1MTBAPF6_-1.2_to_1V_100mVs,Ar,MeCN,0.100,None,TBAPF6
1,MeCN_Ar_0.1MTBAPF6_3mMFc_1mMFe-tpyPY2Me_-1.2_t...,Ar,MeCN,0.100,None,"TBAPF6, Fc, Fe-tpyPY2Me"
2,MeCN_Ar_0.1MTBAPF6_3mMFc_1mMFe-tpyPY2Me_-1.7_t...,Ar,MeCN,0.100,None,"TBAPF6, Fc, Fe-tpyPY2Me"
3,MeCN_Ar_0.1MTBAPF6_3mMFc_1mMFe-tpyPY2Me_-1.7_t...,Ar,MeCN,0.025,None,"TBAPF6, Fc, Fe-tpyPY2Me"
4,MeCN_Ar_0.1MTBAPF6_3mMFc_1mMFe-tpyPY2Me_-1.7_t...,Ar,MeCN,0.500,None,"TBAPF6, Fc, Fe-tpyPY2Me"
5,MeCN_Ar_0.1MTBAPF6_3mMFc_1mMFe-tpyPY2Me_-1.7_t...,Ar,MeCN,1.000,None,"TBAPF6, Fc, Fe-tpyPY2Me"
6,MeCN_Ar_0.1MTBAPF6_3mMFc_1mMFe-tpyPY2Me_-1.7_t...,Ar,MeCN,0.050,None,"TBAPF6, Fc, Fe-tpyPY2Me"
7,MeCN_CO2_0.1MTBAPF6_3mMFc_1mMFe-tpyPY2Me_-1.2_...,CO2,MeCN,0.100,None,"TBAPF6, Fc, Fe-tpyPY2Me"
8,MeCN_CO2_0.1MTBAPF6_3mMFc_1mMFe-tpyPY2Me_100mM...,CO2,MeCN,0.100,None,"TBAPF6, Fc, Fe-tpyPY2Me, PhOH"
9,MeCN_CO2_0.1MTBAPF6_3mMFc_1mMFe-tpyPY2Me_560mM...,CO2,MeCN,0.100,None,"TBAPF6, Fc, Fe-tpyPY2Me, PhOH"
10,MeCN_CO2_0.1MTBAPF6_3mMFc_1mMFe-tpyPY2Me_1MPhO...,CO2,MeCN,0.100,None,"TBAPF6, Fc, Fe-tpyPY2Me, PhOH"
11,MeCN_CO2_0.1MTBAPF6_3mMFc_1mMFe-tpyPY2Me_2.8MP...,CO2,MeCN,0.100,None,"TBAPF6, Fc, Fe-tpyPY2Me, PhOH"

In [5]:
# Inspect options by function. Category-sorted tables make it easier to find relevant knobs.
e.describe_options("get_data", {"pretty print": False, "return": True}).head(20)

            Category                Option                                                        Default                 Type                           Choices                                                                                                                              Description
          Data/input               columns                                                              3                  int                                                                                                                         Number of columns expected in imported data files.
          Data/input             compounds                                                           None       object or None                                                                                                                 Compound names associated with the electrochemical object.
          Data/input         custom reader                                                           None       object or None                                                                                                                       User-provided file reader for custom import formats.
          Data/input               decimal                                                              .                  str                                                                                                                             Decimal separator used in imported text files.
          Data/input             delimiter                                                              ,                  str                                                                                                                              Column delimiter used in imported text files.
          Data/input       experiment type                                                           None          str or None                                                           Experiment type to require or assign. If omitted, eCAT promotes objects from parser/file metadata when possible.
          Data/input           folder path                                                              .                  str                                                                                                                       Folder path searched for electrochemical data files.
          Data/input                   gas                                                           None          str or None                                                                                                                     Gas condition metadata for the electrochemical object.
          Data/input      name alterations                                                           None       object or None                                                                                                                          Filename text replacements applied during import.
          Data/input      recursive search                                                           True                 bool                                                                                                                               Recursively search subfolders during import.
          Data/input              software                                                           None          str or None                                                                 Instrument software/parser. If omitted, import tries to infer the parser from file contents and extension.
          Data/input               solvent                                                           None          str or None                                                                                                                           Solvent metadata for the electrochemical object.
          Data/input             sort keys                                                    [timestamp]               object                                                                                    Sort keys used to order imported objects after parsing and before reference assignment.
          Data/input           temperature                                                            298                float                                                                                          Temperature in K assigned to imported objects when the file does not provide one.
Reference/correction  allow self reference                                                           True                 bool                                                                            Allow a CV to be considered as its own reference candidate during automatic reference shifting.
Reference/correction       peak prominence                                                           None        float or None                                                         Minimum peak prominence for automatic reference-wave detection; None lets peak detection use its internal default.
Reference/correction        reference file                                                           None          str or None                                                                                       Explicit reference file used by reference mode 'file'; no file matching is inferred.
Reference/correction       reference guess                                                           auto float or str or None                                                                             'auto' locates the reference wave automatically; a numeric value searches near that potential.
Reference/correction     reference keyword                                                           None          str or None                                                                                                 Single keyword used by reference mode 'keyword' to choose reference files.
Reference/correction    reference keywords [Fc, ferrocene, decamethylferrocene, DmFc, cobaltocene, CoCp2]    list[str] or None                                                                  Reference keywords tried by reference mode 'auto'; the first successful keyword defines the shift source.
Reference/correction       reference label                                                         Fc/Fc+                  str                                                                                                                                  Axis label used after reference shifting.
Reference/correction         reference map                                                           None         dict or None                                                             Explicit target-to-reference object index mapping; overrides automatic reference assignment for those objects.
Reference/correction        reference mode                                                           auto                  str auto, manual, keyword, file, none 'auto' searches imported files with reference keywords; 'keyword', 'file', and 'manual' use the corresponding explicit reference source.
Reference/correction      reference offset                                                           None        float or None                                                                                                                                         Manual reference potential offset.
Reference/correction           shift guess                                                           auto float or str or None                                                                                     Legacy reference-shift guess. 'auto' locates the shifted reference wave automatically.
Reference/correction           shift label                                                         Fc/Fc+                  str                                                                                                                                Legacy label used after potential shifting.
Reference/correction    shift max delta ep                                                            0.2                float                                                                                                       Maximum reference peak separation allowed during reference matching.
Reference/correction       shift potential                                                          False bool or str or float                                                                                                                      Legacy flag or value for shifting the potential axis.
Reference/correction          shift smooth                                                           True                 bool                                                                                                                         Smooth data before locating reference-shift peaks.
Reference/correction shift target delta ep                                                           0.08                float                                                                                                           Target reference peak separation used during reference matching.
Reference/correction          shift window                                                            0.3                float                                                                                                                     Potential window used to locate reference-shift peaks.
 Units/normalization       convert current                                                          False                 bool                                                                                                            Convert current values to a requested display or analysis unit.
 Units/normalization       current density                                                          False                 bool                                                                                                             Normalize current by electrode area to report current density.
 Units/normalization        electrode area                                                              0                float                                            Electrode area in cm^2 assigned to imported objects; may be computed from electrode diameter when current density is requested.
 Units/normalization    electrode diameter                                                              0                float                                                Electrode diameter in cm used to compute electrode area for current-density conversion when electrode area is not provided.
 Units/normalization        invert current                                                          False                 bool                                                                                                                                                    Multiply current by -1.
      Output/display          pretty print                                                           True                 bool                                                           Use rich table display when printing object lists or summaries. False uses plain-text output when print is True.
      Output/display                 print                                                           True                 bool                                                                                        Whether to emit output. False suppresses output; it is independent of pretty print.
      Output/display          troubleshoot                                                          False                 bool                                                                                                                                   Print additional troubleshooting output.

,Category,Option,Default,Type,Choices,Description
0,Data/input,columns,3,int,,Number of columns expected in imported data fi...
1,Data/input,compounds,None,object or None,,Compound names associated with the electrochem...
2,Data/input,custom reader,None,object or None,,User-provided file reader for custom import fo...
3,Data/input,decimal,.,str,,Decimal separator used in imported text files.
4,Data/input,delimiter,",",str,,Column delimiter used in imported text files.
5,Data/input,experiment type,None,str or None,,Experiment type to require or assign. If omitt...
6,Data/input,folder path,.,str,,Folder path searched for electrochemical data ...
7,Data/input,gas,None,str or None,,Gas condition metadata for the electrochemical...
8,Data/input,name alterations,None,object or None,,Filename text replacements applied during import.
9,Data/input,recursive search,True,bool,,Recursively search subfolders during import.
10,Data/input,software,None,str or None,,"Instrument software/parser. If omitted, import..."
11,Data/input,solvent,None,str or None,,Solvent metadata for the electrochemical object.
12,Data/input,sort keys,[timestamp],object,,Sort keys used to order imported objects after...
13,Data/input,temperature,298,float,,Temperature in K assigned to imported objects ...
14,Reference/correction,allow self reference,True,bool,,Allow a CV to be considered as its own referen...
15,Reference/correction,peak prominence,None,float or None,,Minimum peak prominence for automatic referenc...
16,Reference/correction,reference file,None,str or None,,Explicit reference file used by reference mode...
17,Reference/correction,reference guess,auto,float or str or None,,'auto' locates the reference wave automaticall...
18,Reference/correction,reference keyword,None,str or None,,Single keyword used by reference mode 'keyword...
19,Reference/correction,reference keywords,"[Fc, ferrocene, decamethylferrocene, DmFc, cob...",list[str] or None,,Reference keywords tried by reference mode 'au...

In [6]:
# Missing peak troubleshooting: look at detected peak-related options.
e.describe_options("peak_current", {"pretty print": False, "return": True})

        Category             Option         Default                                               Type                                                                                                                                                                                                                              Description
Fitting/analysis  percent threshold             NaN                                      float or None                                                                                                                                                                                     Percent threshold used in peak or tangent selection.
Fitting/analysis tangent min points             NaN                                        int or None                                                                                                                                  Minimum points for tangent fitting; when omitted, eCAT derives a minimum from the pre-peak data length.
Fitting/analysis  tangent potential             NaN                                      float or None                                                                                                                                            Manual tangent anchor potential; when omitted, eCAT anchors from the resolved tangent region.
Fitting/analysis      tangent range            auto str or float or list[float] or tuple[float, float]                                                                                                                                            'auto' chooses a pre-peak baseline region from derivative/curvature behavior before the peak.
        Advanced      peak fallback highest current                                        str or None Fallback used by peak_current when no local peak is detected. 'highest current' uses the largest absolute current in the selected segment; 'guess potential' treats the guess as an exact potential; None/'none' keeps the strict error.

,Category,Option,Default,Type,Description
0,Fitting/analysis,percent threshold,NaN,float or None,Percent threshold used in peak or tangent sele...
1,Fitting/analysis,tangent min points,NaN,int or None,Minimum points for tangent fitting; when omitt...
2,Fitting/analysis,tangent potential,NaN,float or None,"Manual tangent anchor potential; when omitted,..."
3,Fitting/analysis,tangent range,auto,"str or float or list[float] or tuple[float, fl...",'auto' chooses a pre-peak baseline region from...
4,Advanced,peak fallback,highest current,str or None,Fallback used by peak_current when no local pe...

In [7]:
# Reference-shift troubleshooting. This tutorial subset is unreferenced by design.
e.describe_options("get_data", {"pretty print": False, "return": True}).query("Category == 'Reference/correction'")

            Category                Option                                                        Default                 Type                           Choices                                                                                                                              Description
          Data/input               columns                                                              3                  int                                                                                                                         Number of columns expected in imported data files.
          Data/input             compounds                                                           None       object or None                                                                                                                 Compound names associated with the electrochemical object.
          Data/input         custom reader                                                           None       object or None                                                                                                                       User-provided file reader for custom import formats.
          Data/input               decimal                                                              .                  str                                                                                                                             Decimal separator used in imported text files.
          Data/input             delimiter                                                              ,                  str                                                                                                                              Column delimiter used in imported text files.
          Data/input       experiment type                                                           None          str or None                                                           Experiment type to require or assign. If omitted, eCAT promotes objects from parser/file metadata when possible.
          Data/input           folder path                                                              .                  str                                                                                                                       Folder path searched for electrochemical data files.
          Data/input                   gas                                                           None          str or None                                                                                                                     Gas condition metadata for the electrochemical object.
          Data/input      name alterations                                                           None       object or None                                                                                                                          Filename text replacements applied during import.
          Data/input      recursive search                                                           True                 bool                                                                                                                               Recursively search subfolders during import.
          Data/input              software                                                           None          str or None                                                                 Instrument software/parser. If omitted, import tries to infer the parser from file contents and extension.
          Data/input               solvent                                                           None          str or None                                                                                                                           Solvent metadata for the electrochemical object.
          Data/input             sort keys                                                    [timestamp]               object                                                                                    Sort keys used to order imported objects after parsing and before reference assignment.
          Data/input           temperature                                                            298                float                                                                                          Temperature in K assigned to imported objects when the file does not provide one.
Reference/correction  allow self reference                                                           True                 bool                                                                            Allow a CV to be considered as its own reference candidate during automatic reference shifting.
Reference/correction       peak prominence                                                           None        float or None                                                         Minimum peak prominence for automatic reference-wave detection; None lets peak detection use its internal default.
Reference/correction        reference file                                                           None          str or None                                                                                       Explicit reference file used by reference mode 'file'; no file matching is inferred.
Reference/correction       reference guess                                                           auto float or str or None                                                                             'auto' locates the reference wave automatically; a numeric value searches near that potential.
Reference/correction     reference keyword                                                           None          str or None                                                                                                 Single keyword used by reference mode 'keyword' to choose reference files.
Reference/correction    reference keywords [Fc, ferrocene, decamethylferrocene, DmFc, cobaltocene, CoCp2]    list[str] or None                                                                  Reference keywords tried by reference mode 'auto'; the first successful keyword defines the shift source.
Reference/correction       reference label                                                         Fc/Fc+                  str                                                                                                                                  Axis label used after reference shifting.
Reference/correction         reference map                                                           None         dict or None                                                             Explicit target-to-reference object index mapping; overrides automatic reference assignment for those objects.
Reference/correction        reference mode                                                           auto                  str auto, manual, keyword, file, none 'auto' searches imported files with reference keywords; 'keyword', 'file', and 'manual' use the corresponding explicit reference source.
Reference/correction      reference offset                                                           None        float or None                                                                                                                                         Manual reference potential offset.
Reference/correction           shift guess                                                           auto float or str or None                                                                                     Legacy reference-shift guess. 'auto' locates the shifted reference wave automatically.
Reference/correction           shift label                                                         Fc/Fc+                  str                                                                                                                                Legacy label used after potential shifting.
Reference/correction    shift max delta ep                                                            0.2                float                                                                                                       Maximum reference peak separation allowed during reference matching.
Reference/correction       shift potential                                                          False bool or str or float                                                                                                                      Legacy flag or value for shifting the potential axis.
Reference/correction          shift smooth                                                           True                 bool                                                                                                                         Smooth data before locating reference-shift peaks.
Reference/correction shift target delta ep                                                           0.08                float                                                                                                           Target reference peak separation used during reference matching.
Reference/correction          shift window                                                            0.3                float                                                                                                                     Potential window used to locate reference-shift peaks.
 Units/normalization       convert current                                                          False                 bool                                                                                                            Convert current values to a requested display or analysis unit.
 Units/normalization       current density                                                          False                 bool                                                                                                             Normalize current by electrode area to report current density.
 Units/normalization        electrode area                                                              0                float                                            Electrode area in cm^2 assigned to imported objects; may be computed from electrode diameter when current density is requested.
 Units/normalization    electrode diameter                                                              0                float                                                Electrode diameter in cm used to compute electrode area for current-density conversion when electrode area is not provided.
 Units/normalization        invert current                                                          False                 bool                                                                                                                                                    Multiply current by -1.
      Output/display          pretty print                                                           True                 bool                                                           Use rich table display when printing object lists or summaries. False uses plain-text output when print is True.
      Output/display                 print                                                           True                 bool                                                                                        Whether to emit output. False suppresses output; it is independent of pretty print.
      Output/display          troubleshoot                                                          False                 bool                                                                                                                                   Print additional troubleshooting output.

,Category,Option,Default,Type,Choices,Description
14,Reference/correction,allow self reference,True,bool,,Allow a CV to be considered as its own referen...
15,Reference/correction,peak prominence,None,float or None,,Minimum peak prominence for automatic referenc...
16,Reference/correction,reference file,None,str or None,,Explicit reference file used by reference mode...
17,Reference/correction,reference guess,auto,float or str or None,,'auto' locates the reference wave automaticall...
18,Reference/correction,reference keyword,None,str or None,,Single keyword used by reference mode 'keyword...
19,Reference/correction,reference keywords,"[Fc, ferrocene, decamethylferrocene, DmFc, cob...",list[str] or None,,Reference keywords tried by reference mode 'au...
20,Reference/correction,reference label,Fc/Fc+,str,,Axis label used after reference shifting.
21,Reference/correction,reference map,None,dict or None,,Explicit target-to-reference object index mapp...
22,Reference/correction,reference mode,auto,str,"auto, manual, keyword, file, none",'auto' searches imported files with reference ...
23,Reference/correction,reference offset,None,float or None,,Manual reference potential offset.
24,Reference/correction,shift guess,auto,float or str or None,,Legacy reference-shift guess. 'auto' locates t...
25,Reference/correction,shift label,Fc/Fc+,str,,Legacy label used after potential shifting.
26,Reference/correction,shift max delta ep,0.2,float,,Maximum reference peak separation allowed duri...
27,Reference/correction,shift potential,False,bool or str or float,,Legacy flag or value for shifting the potentia...
28,Reference/correction,shift smooth,True,bool,,Smooth data before locating reference-shift pe...
29,Reference/correction,shift target delta ep,0.08,float,,Target reference peak separation used during r...
30,Reference/correction,shift window,0.3,float,,Potential window used to locate reference-shif...

In [8]:
# Small reproducibility report to paste into an issue/email.
report = {
    "ecat_version": getattr(e, "__version__", "unknown"),
    "data_dir": display_path(DATA_DIR),
    "n_files": len(list(DATA_DIR.glob("*.txt"))),
    "n_loaded": len(cvs),
    "object_types": sorted({type(obj).__name__ for obj in cvs}),
}
report

{'ecat_version': '0.1.0b2',
 'data_dir': 'examples/data/fe_phoh_cv',
 'n_files': 13,
 'n_loaded': 12,
 'object_types': ['cv']}